apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowerapp
  namespace: suwetha-ns 
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      label: flower-app
  template:
    metadata:
      labels:
       app: flower-app
    spec:
      containers:
        - name: flowerimage
          image: suwetha07/flowerwebapp:v1.1.0
          ports:
            - containerPort: 3015
          resources:
            requests:
              cpu: "100Mi"
              memory: "256Mi"
            limit:
              cpu: "200Mi"
              memory: "512Mi"
          envFrom:
            - configMapRef: 
              name: flower-configmap
            - secretRef:
              name: flower-secrets
          # env:
          # - name: MONGO_URI
          #   valueFrom:
          #     configMapKeyRef:
          #       name: flower-configmap
          #       key:  MONGO_URI
          # - name: PORT
          #   valueFrom:
          #     configMapKeyRef:
          #       name: flower-configmap
          #       key:  PORT
          # - name: SESSION_SECRET
          #   valueFrom:
          #     secretKeyRef:
          #     name: flower-secrets
          #     key: SESSION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: flower-Service
  namespace: suwetha-ns
spec:
  selector:
    app: flower-app
  ports:
    - port: 80
      targetPort: 3015
  type: NodePort